<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo><!-- setting GenerateAssemblyInfo to false causes this bug https://github.com/dotnet/project-system/issues/3934 -->
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Tusk</AssemblyName>
    <PackageId>Tusk</PackageId>
    <OutputType>Library</OutputType>
    <Authors>Coldcart</Authors>
    <Company>Coldcart</Company>
    <AssemblyTitle>Tusk SDK Library</AssemblyTitle>
    <Description>Tusk SDK Client for .NET</Description>
    <Copyright>No Copyright</Copyright>
    <RootNamespace>Tusk</RootNamespace>    
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\Tusk.xml</DocumentationFile>
    <RepositoryUrl>https://github.com/coldcart/TuskCSharp</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/coldcart/TuskCSharp</PackageProjectUrl>
    <PackageTags>tusk;logistics;api;sdk</PackageTags>
    <PackageReleaseNotes>Minor update</PackageReleaseNotes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Nullable>annotations</Nullable>
    <VersionPrefix>$([System.DateTime]::Now.ToString("yyyy.MM.dd"))</VersionPrefix>
    <BuildNumber>$([System.DateTime]::Now.ToString("HHmmss"))</BuildNumber>
    <PackageVersion Condition="'$(VersionSuffix)' != ''">$(VersionPrefix).$(BuildNumber)-$(VersionSuffix)</PackageVersion>
    <PackageVersion Condition="'$(VersionSuffix)' == ''">$(VersionPrefix).$(BuildNumber)</PackageVersion>    
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
     <None Include="../../README.md" Pack="true" PackagePath="\"/>
   </ItemGroup>
</Project>
