/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Net.Http;
using Tusk.Client;
using Tusk.Model;

namespace Tusk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITrackingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Label Tracking History
        /// </summary>
        /// <remarks>
        /// Get the full tracking history for a label
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>V1TrackingLabelHistoryResponse</returns>
        V1TrackingLabelHistoryResponse GetLabelTrackingHistory(int labelId);

        /// <summary>
        /// Get Label Tracking History
        /// </summary>
        /// <remarks>
        /// Get the full tracking history for a label
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>ApiResponse of V1TrackingLabelHistoryResponse</returns>
        ApiResponse<V1TrackingLabelHistoryResponse> GetLabelTrackingHistoryWithHttpInfo(int labelId);
        /// <summary>
        /// Get Label Tracking Status
        /// </summary>
        /// <remarks>
        /// Get the latest status and location
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>TrackingLabel</returns>
        TrackingLabel GetLabelTrackingStatus(int labelId);

        /// <summary>
        /// Get Label Tracking Status
        /// </summary>
        /// <remarks>
        /// Get the latest status and location
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>ApiResponse of TrackingLabel</returns>
        ApiResponse<TrackingLabel> GetLabelTrackingStatusWithHttpInfo(int labelId);
        /// <summary>
        /// Get Shipment Tracking
        /// </summary>
        /// <remarks>
        /// Get the tracking history for an entire Shipment
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <returns>TrackingShipment</returns>
        TrackingShipment GetShipmentTracking(string trackingNumber);

        /// <summary>
        /// Get Shipment Tracking
        /// </summary>
        /// <remarks>
        /// Get the tracking history for an entire Shipment
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <returns>ApiResponse of TrackingShipment</returns>
        ApiResponse<TrackingShipment> GetShipmentTrackingWithHttpInfo(string trackingNumber);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITrackingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Label Tracking History
        /// </summary>
        /// <remarks>
        /// Get the full tracking history for a label
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1TrackingLabelHistoryResponse</returns>
        System.Threading.Tasks.Task<V1TrackingLabelHistoryResponse> GetLabelTrackingHistoryAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Label Tracking History
        /// </summary>
        /// <remarks>
        /// Get the full tracking history for a label
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1TrackingLabelHistoryResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<V1TrackingLabelHistoryResponse>> GetLabelTrackingHistoryWithHttpInfoAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get Label Tracking Status
        /// </summary>
        /// <remarks>
        /// Get the latest status and location
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TrackingLabel</returns>
        System.Threading.Tasks.Task<TrackingLabel> GetLabelTrackingStatusAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Label Tracking Status
        /// </summary>
        /// <remarks>
        /// Get the latest status and location
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TrackingLabel)</returns>
        System.Threading.Tasks.Task<ApiResponse<TrackingLabel>> GetLabelTrackingStatusWithHttpInfoAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Get Shipment Tracking
        /// </summary>
        /// <remarks>
        /// Get the tracking history for an entire Shipment
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TrackingShipment</returns>
        System.Threading.Tasks.Task<TrackingShipment> GetShipmentTrackingAsync(string trackingNumber, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Get Shipment Tracking
        /// </summary>
        /// <remarks>
        /// Get the tracking history for an entire Shipment
        /// </remarks>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TrackingShipment)</returns>
        System.Threading.Tasks.Task<ApiResponse<TrackingShipment>> GetShipmentTrackingWithHttpInfoAsync(string trackingNumber, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITrackingApi : ITrackingApiSync, ITrackingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TrackingApi : IDisposable, ITrackingApi
    {
        private Tusk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public TrackingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public TrackingApi(string basePath)
        {
            this.Configuration = Tusk.Client.ReadableConfiguration.MergeConfigurations(
                Tusk.Client.GlobalReadableConfiguration.Instance,
                new Tusk.Client.ReadableConfiguration { BasePath = basePath }
            );
            this.ApiClient = new Tusk.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Tusk.Client.ReadableConfiguration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="readableConfiguration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public TrackingApi(Tusk.Client.ReadableConfiguration readableConfiguration)
        {
            if (readableConfiguration == null) throw new ArgumentNullException("readableConfiguration");

            this.Configuration = Tusk.Client.ReadableConfiguration.MergeConfigurations(
                Tusk.Client.GlobalReadableConfiguration.Instance,
                readableConfiguration
            );
            this.ApiClient = new Tusk.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Tusk.Client.ReadableConfiguration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TrackingApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TrackingApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Tusk.Client.ReadableConfiguration.MergeConfigurations(
                Tusk.Client.GlobalReadableConfiguration.Instance,
                new Tusk.Client.ReadableConfiguration { BasePath = basePath }
            );
            this.ApiClient = new Tusk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Tusk.Client.ReadableConfiguration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="readableConfiguration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public TrackingApi(HttpClient client, Tusk.Client.ReadableConfiguration readableConfiguration, HttpClientHandler handler = null)
        {
            if (readableConfiguration == null) throw new ArgumentNullException("readableConfiguration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Tusk.Client.ReadableConfiguration.MergeConfigurations(
                Tusk.Client.GlobalReadableConfiguration.Instance,
                readableConfiguration
            );
            this.ApiClient = new Tusk.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Tusk.Client.ReadableConfiguration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public TrackingApi(Tusk.Client.ISynchronousClient client, Tusk.Client.IAsynchronousClient asyncClient, Tusk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Tusk.Client.ReadableConfiguration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Tusk.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Tusk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Tusk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Tusk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Tusk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Label Tracking History Get the full tracking history for a label
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>V1TrackingLabelHistoryResponse</returns>
        public V1TrackingLabelHistoryResponse GetLabelTrackingHistory(int labelId)
        {
            Tusk.Client.ApiResponse<V1TrackingLabelHistoryResponse> localVarResponse = GetLabelTrackingHistoryWithHttpInfo(labelId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Label Tracking History Get the full tracking history for a label
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>ApiResponse of V1TrackingLabelHistoryResponse</returns>
        public Tusk.Client.ApiResponse<V1TrackingLabelHistoryResponse> GetLabelTrackingHistoryWithHttpInfo(int labelId)
        {
            Tusk.Client.RequestOptions localVarRequestOptions = new Tusk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Tusk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Tusk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("label_id", Tusk.Client.ClientUtils.ParameterToString(labelId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<V1TrackingLabelHistoryResponse>("/v1/tracking/label/{label_id}/history", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLabelTrackingHistory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Label Tracking History Get the full tracking history for a label
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of V1TrackingLabelHistoryResponse</returns>
        public async System.Threading.Tasks.Task<V1TrackingLabelHistoryResponse> GetLabelTrackingHistoryAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Tusk.Client.ApiResponse<V1TrackingLabelHistoryResponse> localVarResponse = await GetLabelTrackingHistoryWithHttpInfoAsync(labelId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Label Tracking History Get the full tracking history for a label
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (V1TrackingLabelHistoryResponse)</returns>
        public async System.Threading.Tasks.Task<Tusk.Client.ApiResponse<V1TrackingLabelHistoryResponse>> GetLabelTrackingHistoryWithHttpInfoAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Tusk.Client.RequestOptions localVarRequestOptions = new Tusk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Tusk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Tusk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("label_id", Tusk.Client.ClientUtils.ParameterToString(labelId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<V1TrackingLabelHistoryResponse>("/v1/tracking/label/{label_id}/history", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLabelTrackingHistory", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Label Tracking Status Get the latest status and location
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>TrackingLabel</returns>
        public TrackingLabel GetLabelTrackingStatus(int labelId)
        {
            Tusk.Client.ApiResponse<TrackingLabel> localVarResponse = GetLabelTrackingStatusWithHttpInfo(labelId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Label Tracking Status Get the latest status and location
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <returns>ApiResponse of TrackingLabel</returns>
        public Tusk.Client.ApiResponse<TrackingLabel> GetLabelTrackingStatusWithHttpInfo(int labelId)
        {
            Tusk.Client.RequestOptions localVarRequestOptions = new Tusk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Tusk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Tusk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("label_id", Tusk.Client.ClientUtils.ParameterToString(labelId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TrackingLabel>("/v1/tracking/label/{label_id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLabelTrackingStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Label Tracking Status Get the latest status and location
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TrackingLabel</returns>
        public async System.Threading.Tasks.Task<TrackingLabel> GetLabelTrackingStatusAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Tusk.Client.ApiResponse<TrackingLabel> localVarResponse = await GetLabelTrackingStatusWithHttpInfoAsync(labelId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Label Tracking Status Get the latest status and location
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="labelId">LabelID to return tracking for</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TrackingLabel)</returns>
        public async System.Threading.Tasks.Task<Tusk.Client.ApiResponse<TrackingLabel>> GetLabelTrackingStatusWithHttpInfoAsync(int labelId, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Tusk.Client.RequestOptions localVarRequestOptions = new Tusk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Tusk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Tusk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("label_id", Tusk.Client.ClientUtils.ParameterToString(labelId)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TrackingLabel>("/v1/tracking/label/{label_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetLabelTrackingStatus", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Shipment Tracking Get the tracking history for an entire Shipment
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <returns>TrackingShipment</returns>
        public TrackingShipment GetShipmentTracking(string trackingNumber)
        {
            Tusk.Client.ApiResponse<TrackingShipment> localVarResponse = GetShipmentTrackingWithHttpInfo(trackingNumber);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Shipment Tracking Get the tracking history for an entire Shipment
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <returns>ApiResponse of TrackingShipment</returns>
        public Tusk.Client.ApiResponse<TrackingShipment> GetShipmentTrackingWithHttpInfo(string trackingNumber)
        {
            // verify the required parameter 'trackingNumber' is set
            if (trackingNumber == null)
                throw new Tusk.Client.ApiException(400, "Missing required parameter 'trackingNumber' when calling TrackingApi->GetShipmentTracking");

            Tusk.Client.RequestOptions localVarRequestOptions = new Tusk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Tusk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Tusk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tracking_number", Tusk.Client.ClientUtils.ParameterToString(trackingNumber)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TrackingShipment>("/v1/tracking/{tracking_number}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetShipmentTracking", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Shipment Tracking Get the tracking history for an entire Shipment
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TrackingShipment</returns>
        public async System.Threading.Tasks.Task<TrackingShipment> GetShipmentTrackingAsync(string trackingNumber, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Tusk.Client.ApiResponse<TrackingShipment> localVarResponse = await GetShipmentTrackingWithHttpInfoAsync(trackingNumber, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Shipment Tracking Get the tracking history for an entire Shipment
        /// </summary>
        /// <exception cref="Tusk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trackingNumber">Tracking number for the Shipment</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TrackingShipment)</returns>
        public async System.Threading.Tasks.Task<Tusk.Client.ApiResponse<TrackingShipment>> GetShipmentTrackingWithHttpInfoAsync(string trackingNumber, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'trackingNumber' is set
            if (trackingNumber == null)
                throw new Tusk.Client.ApiException(400, "Missing required parameter 'trackingNumber' when calling TrackingApi->GetShipmentTracking");


            Tusk.Client.RequestOptions localVarRequestOptions = new Tusk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Tusk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Tusk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("tracking_number", Tusk.Client.ClientUtils.ParameterToString(trackingNumber)); // path parameter

            // authentication (ApiKeyAuth) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<TrackingShipment>("/v1/tracking/{tracking_number}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetShipmentTracking", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
