/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// APIError
    /// </summary>
    [DataContract(Name = "APIError")]
    public partial class APIError : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="APIError" /> class.
        /// </summary>
        /// <param name="errors">Further information about the error which has occurred..</param>
        /// <param name="type">type.</param>
        /// <param name="title">The error which has occurred..</param>
        /// <param name="status">Status code of the response..</param>
        public APIError(Object errors = default(Object), string type = default(string), string title = default(string), decimal status = default(decimal))
        {
            this.Errors = errors;
            this.Type = type;
            this.Title = title;
            this.Status = status;
        }

        /// <summary>
        /// Further information about the error which has occurred.
        /// </summary>
        /// <value>Further information about the error which has occurred.</value>
        [DataMember(Name = "errors", EmitDefaultValue = false)]
        [JsonPropertyName("errors")]
        public Object Errors { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        [JsonPropertyName("type")]
        public string Type { get; set; }

        /// <summary>
        /// The error which has occurred.
        /// </summary>
        /// <value>The error which has occurred.</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Status code of the response.
        /// </summary>
        /// <value>Status code of the response.</value>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        [JsonPropertyName("status")]
        public decimal Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class APIError {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
