/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// Package dimensions.
    /// </summary>
    [DataContract(Name = "Dimensions")]
    public partial class Dimensions : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Dimensions" /> class.
        /// </summary>
        [JsonConstructor]
        public Dimensions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Dimensions" /> class.
        /// </summary>
        /// <param name="length">Length in inches. (required).</param>
        /// <param name="width">Width in inches. (required).</param>
        /// <param name="height">Height in inches. (required).</param>
        public Dimensions(decimal length = default(decimal), decimal width = default(decimal), decimal height = default(decimal))
        {
            this.Length = length;
            this.Width = width;
            this.Height = height;
        }

        /// <summary>
        /// Length in inches.
        /// </summary>
        /// <value>Length in inches.</value>
        [DataMember(Name = "length", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("length")]
        public decimal Length { get; set; }

        /// <summary>
        /// Width in inches.
        /// </summary>
        /// <value>Width in inches.</value>
        [DataMember(Name = "width", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("width")]
        public decimal Width { get; set; }

        /// <summary>
        /// Height in inches.
        /// </summary>
        /// <value>Height in inches.</value>
        [DataMember(Name = "height", IsRequired = true, EmitDefaultValue = true)]
        [JsonPropertyName("height")]
        public decimal Height { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Dimensions {\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Width: ").Append(Width).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
