/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// ManifestOperationResponse
    /// </summary>
    [DataContract(Name = "ManifestOperationResponse")]
    public partial class ManifestOperationResponse : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ManifestOperationResponse" /> class.
        /// </summary>
        /// <param name="manifestId">The identifier of this Manifest..</param>
        /// <param name="exceptions">exceptions.</param>
        public ManifestOperationResponse(int manifestId = default(int), List<ManifestException> exceptions = default(List<ManifestException>))
        {
            this.ManifestId = manifestId;
            this.Exceptions = exceptions;
        }

        /// <summary>
        /// The identifier of this Manifest.
        /// </summary>
        /// <value>The identifier of this Manifest.</value>
        [DataMember(Name = "manifest_id", EmitDefaultValue = false)]
        [JsonPropertyName("manifest_id")]
        public int ManifestId { get; set; }

        /// <summary>
        /// Gets or Sets Exceptions
        /// </summary>
        [DataMember(Name = "exceptions", EmitDefaultValue = false)]
        [JsonPropertyName("exceptions")]
        public List<ManifestException> Exceptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ManifestOperationResponse {\n");
            sb.Append("  ManifestId: ").Append(ManifestId).Append("\n");
            sb.Append("  Exceptions: ").Append(Exceptions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
