/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// ParcelWeight
    /// </summary>
    [DataContract(Name = "Parcel_weight")]
    public partial class ParcelWeight : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelWeight" /> class.
        /// </summary>
        [JsonConstructor]
        public ParcelWeight() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ParcelWeight" /> class.
        /// </summary>
        /// <param name="value">Weight amount, in unit specified. (required).</param>
        /// <param name="unit">Unit of weight. Specify \&quot;Pound\&quot; or \&quot;Ounce\&quot;. Responses from this Api will be in ounces. (required).</param>
        public ParcelWeight(decimal value = default(decimal), string unit = default(string))
        {
            this.Value = value;
            // to ensure "unit" is required (not null)
            if (unit == null)
            {
                throw new ArgumentNullException("unit is a required property for ParcelWeight and cannot be null");
            }
            this.Unit = unit;
        }

        /// <summary>
        /// Weight amount, in unit specified.
        /// </summary>
        /// <value>Weight amount, in unit specified.</value>
        [DataMember(Name = "value", EmitDefaultValue = true)]
        [JsonPropertyName("value")]
        public decimal Value { get; set; }

        /// <summary>
        /// Unit of weight. Specify \&quot;Pound\&quot; or \&quot;Ounce\&quot;. Responses from this Api will be in ounces.
        /// </summary>
        /// <value>Unit of weight. Specify \&quot;Pound\&quot; or \&quot;Ounce\&quot;. Responses from this Api will be in ounces.</value>
        [DataMember(Name = "unit", EmitDefaultValue = true)]
        [JsonPropertyName("unit")]
        public string? Unit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ParcelWeight {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  Unit: ").Append(Unit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
