/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// Shipment
    /// </summary>
    [DataContract(Name = "Shipment")]
    public partial class Shipment : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Shipment" /> class.
        /// </summary>
        /// <param name="id">ID of the Shipment..</param>
        /// <param name="externalReference">Optional field for providing an identifier of the shipment. This can help identify shipments faster in case of a support issue. This field is limited to 50 characters and no validation of any data is performed on this..</param>
        /// <param name="confirmation">Confirmation requested for this shipment. Options are: NONE, SIGNATURE, ADULT_SIGNATURE. Defaults to NONE if not specified. A surcharge might apply..</param>
        /// <param name="addressTo">addressTo.</param>
        /// <param name="addressFrom">addressFrom.</param>
        /// <param name="parcels">Parcels sent as part of this Shipment..</param>
        public Shipment(int id = default(int), string externalReference = default(string), string confirmation = default(string), Address addressTo = default(Address), Address addressFrom = default(Address), List<Parcel> parcels = default(List<Parcel>))
        {
            this.Id = id;
            this.ExternalReference = externalReference;
            this.Confirmation = confirmation;
            this.AddressTo = addressTo;
            this.AddressFrom = addressFrom;
            this.Parcels = parcels;
        }

        /// <summary>
        /// ID of the Shipment.
        /// </summary>
        /// <value>ID of the Shipment.</value>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        [JsonPropertyName("id")]
        public int Id { get; set; }

        /// <summary>
        /// Optional field for providing an identifier of the shipment. This can help identify shipments faster in case of a support issue. This field is limited to 50 characters and no validation of any data is performed on this.
        /// </summary>
        /// <value>Optional field for providing an identifier of the shipment. This can help identify shipments faster in case of a support issue. This field is limited to 50 characters and no validation of any data is performed on this.</value>
        [DataMember(Name = "external_reference", EmitDefaultValue = false)]
        [JsonPropertyName("external_reference")]
        public string ExternalReference { get; set; }

        /// <summary>
        /// Confirmation requested for this shipment. Options are: NONE, SIGNATURE, ADULT_SIGNATURE. Defaults to NONE if not specified. A surcharge might apply.
        /// </summary>
        /// <value>Confirmation requested for this shipment. Options are: NONE, SIGNATURE, ADULT_SIGNATURE. Defaults to NONE if not specified. A surcharge might apply.</value>
        [DataMember(Name = "confirmation", EmitDefaultValue = false)]
        [JsonPropertyName("confirmation")]
        public string Confirmation { get; set; }

        /// <summary>
        /// Gets or Sets AddressTo
        /// </summary>
        [DataMember(Name = "address_to", EmitDefaultValue = false)]
        [JsonPropertyName("address_to")]
        public Address AddressTo { get; set; }

        /// <summary>
        /// Gets or Sets AddressFrom
        /// </summary>
        [DataMember(Name = "address_from", EmitDefaultValue = false)]
        [JsonPropertyName("address_from")]
        public Address AddressFrom { get; set; }

        /// <summary>
        /// Parcels sent as part of this Shipment.
        /// </summary>
        /// <value>Parcels sent as part of this Shipment.</value>
        [DataMember(Name = "parcels", EmitDefaultValue = false)]
        [JsonPropertyName("parcels")]
        public List<Parcel> Parcels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Shipment {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ExternalReference: ").Append(ExternalReference).Append("\n");
            sb.Append("  Confirmation: ").Append(Confirmation).Append("\n");
            sb.Append("  AddressTo: ").Append(AddressTo).Append("\n");
            sb.Append("  AddressFrom: ").Append(AddressFrom).Append("\n");
            sb.Append("  Parcels: ").Append(Parcels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
