/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// TrackingShipmentLabel
    /// </summary>
    [DataContract(Name = "TrackingShipmentLabel")]
    public partial class TrackingShipmentLabel : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingShipmentLabel" /> class.
        /// </summary>
        [JsonConstructor]
        public TrackingShipmentLabel()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingShipmentLabel" /> class.
        /// </summary>
        /// <param name="labelId">labelId.</param>
        /// <param name="finalMileCarrier">finalMileCarrier.</param>
        /// <param name="finalMileCarrierTrackingNumber">finalMileCarrierTrackingNumber.</param>
        /// <param name="estimatedDeliveryDate">Estimated delivery date. Null when an estimate cannot be determined or is not applicable..</param>
        /// <param name="trackingEvents">trackingEvents.</param>
        public TrackingShipmentLabel(int labelId = default(int), string finalMileCarrier = default(string), string finalMileCarrierTrackingNumber = default(string), string estimatedDeliveryDate = default(string), List<TrackingEvent> trackingEvents = default(List<TrackingEvent>))
        {
            this.LabelId = labelId;
            this.FinalMileCarrier = finalMileCarrier;
            this.FinalMileCarrierTrackingNumber = finalMileCarrierTrackingNumber;
            this.EstimatedDeliveryDate = estimatedDeliveryDate;
            this.TrackingEvents = trackingEvents;
        }

        /// <summary>
        /// Gets or Sets LabelId
        /// </summary>
        [DataMember(Name = "label_id", EmitDefaultValue = false)]
        [JsonPropertyName("label_id")]
        public int LabelId { get; set; }

        /// <summary>
        /// Gets or Sets FinalMileCarrier
        /// </summary>
        [DataMember(Name = "final_mile_carrier", EmitDefaultValue = false)]
        [JsonPropertyName("final_mile_carrier")]
        public string? FinalMileCarrier { get; set; }

        /// <summary>
        /// Gets or Sets FinalMileCarrierTrackingNumber
        /// </summary>
        [DataMember(Name = "final_mile_carrier_tracking_number", EmitDefaultValue = false)]
        [JsonPropertyName("final_mile_carrier_tracking_number")]
        public string? FinalMileCarrierTrackingNumber { get; set; }

        /// <summary>
        /// Estimated delivery date. Null when an estimate cannot be determined or is not applicable.
        /// </summary>
        /// <value>Estimated delivery date. Null when an estimate cannot be determined or is not applicable.</value>
        [DataMember(Name = "estimated_delivery_date", EmitDefaultValue = true)]
        [JsonPropertyName("estimated_delivery_date")]
        public string? EstimatedDeliveryDate { get; set; }

        /// <summary>
        /// Gets or Sets TrackingEvents
        /// </summary>
        [DataMember(Name = "tracking_events", EmitDefaultValue = false)]
        [JsonPropertyName("tracking_events")]
        public List<TrackingEvent>? TrackingEvents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackingShipmentLabel {\n");
            sb.Append("  LabelId: ").Append(LabelId).Append("\n");
            sb.Append("  FinalMileCarrier: ").Append(FinalMileCarrier).Append("\n");
            sb.Append("  FinalMileCarrierTrackingNumber: ").Append(FinalMileCarrierTrackingNumber).Append("\n");
            sb.Append("  EstimatedDeliveryDate: ").Append(EstimatedDeliveryDate).Append("\n");
            sb.Append("  TrackingEvents: ").Append(TrackingEvents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
