/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// TrackingShipment
    /// </summary>
    [DataContract(Name = "TrackingShipment")]
    public partial class TrackingShipment : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingShipment" /> class.
        /// </summary>
        [JsonConstructor]
        public TrackingShipment()
        {
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackingShipment" /> class.
        /// </summary>
        /// <param name="shipmentId">shipmentId.</param>
        /// <param name="trackingNumber">trackingNumber.</param>
        /// <param name="labels">labels.</param>
        /// <param name="addressFrom">addressFrom.</param>
        /// <param name="addressTo">addressTo.</param>
        public TrackingShipment(int shipmentId = default(int), string trackingNumber = default(string), List<TrackingShipmentLabel> labels = default(List<TrackingShipmentLabel>), TrackingShipmentLocation addressFrom = default(TrackingShipmentLocation), TrackingShipmentLocation addressTo = default(TrackingShipmentLocation))
        {
            this.ShipmentId = shipmentId;
            this.TrackingNumber = trackingNumber;
            this.Labels = labels;
            this.AddressFrom = addressFrom;
            this.AddressTo = addressTo;
        }

        /// <summary>
        /// Gets or Sets ShipmentId
        /// </summary>
        [DataMember(Name = "shipment_id", EmitDefaultValue = false)]
        [JsonPropertyName("shipment_id")]
        public int? ShipmentId { get; set; }

        /// <summary>
        /// Gets or Sets TrackingNumber
        /// </summary>
        [DataMember(Name = "tracking_number", EmitDefaultValue = false)]
        [JsonPropertyName("tracking_number")]
        public string? TrackingNumber { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name = "labels", EmitDefaultValue = false)]
        [JsonPropertyName("labels")]
        public List<TrackingShipmentLabel>? Labels { get; set; }

        /// <summary>
        /// Gets or Sets AddressFrom
        /// </summary>
        [DataMember(Name = "address_from", EmitDefaultValue = false)]
        [JsonPropertyName("address_from")]
        public TrackingShipmentLocation? AddressFrom { get; set; }

        /// <summary>
        /// Gets or Sets AddressTo
        /// </summary>
        [DataMember(Name = "address_to", EmitDefaultValue = false)]
        [JsonPropertyName("address_to")]
        public TrackingShipmentLocation? AddressTo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackingShipment {\n");
            sb.Append("  ShipmentId: ").Append(ShipmentId).Append("\n");
            sb.Append("  TrackingNumber: ").Append(TrackingNumber).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
