/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// V1LabelsRequest
    /// </summary>
    [DataContract(Name = "V1LabelsRequest")]
    public partial class V1LabelsRequest : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1LabelsRequest" /> class.
        /// </summary>
        [JsonConstructor]
        public V1LabelsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1LabelsRequest" /> class.
        /// </summary>
        /// <param name="labelFormat">Format of labels to be returned from this purchase. Options are: PDF4X5, ZPL4X5. Defaults to PDF4X5 if not specified..</param>
        /// <param name="shipment">shipment (required).</param>
        /// <param name="finalMileCarrier">Generate a label for a specific final mile carrier. If nothing is specified, the default carrier will be used.</param>
        public V1LabelsRequest(string labelFormat = default(string), CreateShipment shipment = default(CreateShipment), string finalMileCarrier = default(string))
        {
            // to ensure "shipment" is required (not null)
            if (shipment == null)
            {
                throw new ArgumentNullException("shipment is a required property for V1LabelsRequest and cannot be null");
            }
            this.Shipment = shipment;
            this.LabelFormat = labelFormat;
            this.FinalMileCarrier = finalMileCarrier;
        }
        
        /// <summary>
        /// Generate a label for a specific final mile carrier. If nothing is specified, the default carrier will be used.
        /// <value>
        /// Options are:
        /// cdl,
        /// gls-us,
        /// lso,
        /// uds,
        /// courier_express,
        /// optima,
        /// groscale,
        /// speedx,
        /// uniuni
        /// </value>
        /// </summary>
        [DataMember(Name = "final_mile_carrier", EmitDefaultValue = false)]
        [JsonPropertyName("final_mile_carrier")]
        public string? FinalMileCarrier { get; set; }

        /// <summary>
        /// Format of labels to be returned from this purchase. Options are: PDF4X5, ZPL4X5. Defaults to PDF4X5 if not specified.
        /// </summary>
        /// <value>Format of labels to be returned from this purchase. Options are: PDF4X5, ZPL4X5. Defaults to PDF4X5 if not specified.</value>
        [DataMember(Name = "label_format", EmitDefaultValue = false)]
        [JsonPropertyName("label_format")]
        public string? LabelFormat { get; set; }

        /// <summary>
        /// Gets or Sets Shipment
        /// </summary>
        [DataMember(Name = "shipment", EmitDefaultValue = true)]
        [JsonPropertyName("shipment")]
        public CreateShipment? Shipment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1LabelsRequest {\n");
            sb.Append("  LabelFormat: ").Append(LabelFormat).Append("\n");
            sb.Append("  Shipment: ").Append(Shipment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
