/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// V1ManifestAddlabelsRequest
    /// </summary>
    [DataContract(Name = "V1ManifestAddlabelsRequest")]
    public partial class V1ManifestAddlabelsRequest : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1ManifestAddlabelsRequest" /> class.
        /// </summary>
        [JsonConstructor]
        public V1ManifestAddlabelsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1ManifestAddlabelsRequest" /> class.
        /// </summary>
        /// <param name="labelIds">Label Id to add to manifest.</param>
        /// <param name="shipmentTrackingNumbers">Shipments to add to manifest.</param>
        public V1ManifestAddlabelsRequest(List<int> labelIds = default(List<int>), List<string> shipmentTrackingNumbers = default(List<string>))
        {
            this.LabelIds = labelIds;
            this.ShipmentTrackingNumbers = shipmentTrackingNumbers;
        }

        /// <summary>
        /// Label Id to add to manifest
        /// </summary>
        /// <value>Label Id to add to manifest</value>
        [DataMember(Name = "label_ids", EmitDefaultValue = false)]
        [JsonPropertyName("label_ids")]
        public List<int>? LabelIds { get; set; }

        /// <summary>
        /// Shipments to add to manifest
        /// </summary>
        /// <value>Shipments to add to manifest</value>
        [DataMember(Name = "shipment_tracking_numbers", EmitDefaultValue = false)]
        [JsonPropertyName("shipment_tracking_numbers")]
        public List<string>? ShipmentTrackingNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1ManifestAddlabelsRequest {\n");
            sb.Append("  LabelIds: ").Append(LabelIds).Append("\n");
            sb.Append("  ShipmentTrackingNumbers: ").Append(ShipmentTrackingNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
