/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// V1ManifestRemovelabelsRequest
    /// </summary>
    [DataContract(Name = "V1ManifestRemovelabelsRequest")]
    public partial class V1ManifestRemovelabelsRequest : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of <see cref="V1ManifestRemovelabelsRequest"/>
        /// </summary>
        [JsonConstructor]
        public V1ManifestRemovelabelsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1ManifestRemovelabelsRequest" /> class.
        /// </summary>
        /// <param name="labelIds">Label Id to remove from manifest.</param>
        /// <param name="shipmentTrackingNumbers">Shipments to remove to manifest.</param>
        public V1ManifestRemovelabelsRequest(List<int> labelIds = default(List<int>), List<string> shipmentTrackingNumbers = default(List<string>))
        {
            this.LabelIds = labelIds;
            this.ShipmentTrackingNumbers = shipmentTrackingNumbers;
        }

        /// <summary>
        /// Label Id to remove from manifest
        /// </summary>
        /// <value>Label Id to remove from manifest</value>
        [DataMember(Name = "label_ids", EmitDefaultValue = false)]
        [JsonPropertyName("label_ids")]
        public List<int>? LabelIds { get; set; }

        /// <summary>
        /// Shipments to remove to manifest
        /// </summary>
        /// <value>Shipments to remove to manifest</value>
        [DataMember(Name = "shipment_tracking_numbers", EmitDefaultValue = false)]
        [JsonPropertyName("shipment_tracking_numbers")]
        public List<string>? ShipmentTrackingNumbers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1ManifestRemovelabelsRequest {\n");
            sb.Append("  LabelIds: ").Append(LabelIds).Append("\n");
            sb.Append("  ShipmentTrackingNumbers: ").Append(ShipmentTrackingNumbers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
