/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Text.Json.Serialization;

namespace Tusk.Model
{
    /// <summary>
    /// V1TrackingLabelHistoryResponse
    /// </summary>
    [DataContract(Name = "V1TrackingLabelHistoryResponse")]
    public partial class V1TrackingLabelHistoryResponse : BaseModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TrackingLabelHistoryResponse" /> class.
        /// </summary>
        /// <param name="trackingEvents">trackingEvents.</param>
        public V1TrackingLabelHistoryResponse(List<TrackingLabelHistory> trackingEvents = default(List<TrackingLabelHistory>))
        {
            this.TrackingEvents = trackingEvents;
        }

        /// <summary>
        /// Gets or Sets TrackingEvents
        /// </summary>
        [DataMember(Name = "tracking_events", EmitDefaultValue = false)]
        [JsonPropertyName("tracking_events")]
        public List<TrackingLabelHistory> TrackingEvents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1TrackingLabelHistoryResponse {\n");
            sb.Append("  TrackingEvents: ").Append(TrackingEvents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }

}
