/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Threading.Tasks;
using Xunit;

using Tusk.Client;
using Tusk.Api;
using Tusk.Model;
using Xunit.Abstractions;

// uncomment below to import models
//using Tusk.Model;

namespace Tusk.Test.Api
{
    /// <summary>
    ///  Class for testing LabelsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LabelsApiTests : IDisposable
    {
        private readonly ITestOutputHelper _testOutputHelper;
        private LabelsApi instance;

        public LabelsApiTests(ITestOutputHelper testOutputHelper)
        {
            _testOutputHelper = testOutputHelper;
            ReadableConfiguration config = new ReadableConfiguration();
            config.BasePath = "https://api.tusklogistics.com";
            // Configure API key authorization: ApiKeyAuth
            config.ApiKey.Add("x-api-key", "X_API_KEY");
            HttpClient httpClient = new HttpClient();
            HttpClientHandler httpClientHandler = new HttpClientHandler();
            instance = new LabelsApi(httpClient, config, httpClientHandler);
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LabelsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LabelsApi
            //Assert.IsType<LabelsApi>(instance);
        }

        /// <summary>
        /// Test GetaLabelbyID
        /// </summary>
        [Fact]
        public void GetaLabelbyIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int labelId = null;
            //var response = instance.GetaLabelbyID(labelId);
            //Assert.IsType<Label>(response);
        }

        /// <summary>
        /// Test PurchaseLabels
        /// </summary>
        [Fact()]
        public async Task PurchaseLabelsTest()
        {
            V1LabelsRequest? v1LabelsRequest = new V1LabelsRequest
            {
                Shipment = new CreateShipment
                {
                    Parcels = new List<Parcel>
                    {
                        new Parcel()
                        {
                            Dimensions = new ParcelDimensions
                            {
                                Height = Math.Ceiling(8.63m),
                                Width = Math.Ceiling(8.63m),
                                Length = Math.Ceiling(8.63m),
                            },
                            Weight = new ParcelWeight
                            {
                                Unit = "Pound",
                                Value = Math.Ceiling(1.0m)
                            }
                        }
                    },
                    AddressTo = new Address
                    {
                        Name = "Dave",
                        Street1 = "2026 Jenna Place",
                        Street2 = "",
                        City = "Escondido",
                        State = "CA",
                        PostalCode = "92029",
                        Country = "US",
                        Phone = "773-123-4567",
                        Email = "dave@email.com",
                    },
                    AddressFrom = new Address
                    {
                        Street1 = "2331 Sturgis Rd",
                        City = "Oxnard",
                        State = "CA",
                        PostalCode = "93030",
                    },
                    ExternalReference = "12341212",
                },
                LabelFormat = "PNG4X5"
            };
            _testOutputHelper.WriteLine("PurchaseLabelsTest v1LabelsRequest: " + v1LabelsRequest.ToString());
            var response = await instance.PurchaseLabelsAsync(v1LabelsRequest);
            await instance.VoidaLabelAsync(response.Labels[0].Id);
            //Assert.IsType<ShipmentPurchaseResponse>(response);
        }

        /// <summary>
        /// Test VoidaLabel
        /// </summary>
        [Fact]
        public void VoidaLabelTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int labelId = null;
            //instance.VoidaLabel(labelId);
        }
    }
}
