/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Tusk.Client;
using Tusk.Api;
// uncomment below to import models
//using Tusk.Model;

namespace Tusk.Test.Api
{
    /// <summary>
    ///  Class for testing ManifestApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ManifestApiTests : IDisposable
    {
        private ManifestApi instance;

        public ManifestApiTests()
        {
            instance = new ManifestApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManifestApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ManifestApi
            //Assert.IsType<ManifestApi>(instance);
        }

        /// <summary>
        /// Test AddLabelstoManifest
        /// </summary>
        [Fact]
        public void AddLabelstoManifestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int manifestId = null;
            //V1ManifestAddlabelsRequest? v1ManifestAddlabelsRequest = null;
            //var response = instance.AddLabelstoManifest(manifestId, v1ManifestAddlabelsRequest);
            //Assert.IsType<ManifestOperationResponse>(response);
        }

        /// <summary>
        /// Test CreateaManifest
        /// </summary>
        [Fact]
        public void CreateaManifestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1ManifestCreateRequest? v1ManifestCreateRequest = null;
            //var response = instance.CreateaManifest(v1ManifestCreateRequest);
            //Assert.IsType<ManifestOperationResponse>(response);
        }

        /// <summary>
        /// Test GetaManifestbyID
        /// </summary>
        [Fact]
        public void GetaManifestbyIDTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int manifestId = null;
            //var response = instance.GetaManifestbyID(manifestId);
            //Assert.IsType<Manifest>(response);
        }

        /// <summary>
        /// Test RemoveLabelsfromManifest
        /// </summary>
        [Fact]
        public void RemoveLabelsfromManifestTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int manifestId = null;
            //V1ManifestRemovelabelsRequest? v1ManifestRemovelabelsRequest = null;
            //var response = instance.RemoveLabelsfromManifest(manifestId, v1ManifestRemovelabelsRequest);
            //Assert.IsType<ManifestOperationResponse>(response);
        }
    }
}
