/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Tusk.Client;
using Tusk.Api;
// uncomment below to import models
//using Tusk.Model;

namespace Tusk.Test.Api
{
    /// <summary>
    ///  Class for testing RatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class RatesApiTests : IDisposable
    {
        private RatesApi instance;

        public RatesApiTests()
        {
            instance = new RatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' RatesApi
            //Assert.IsType<RatesApi>(instance);
        }

        /// <summary>
        /// Test CheckRates
        /// </summary>
        [Fact]
        public void CheckRatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1RateCheckRequest? v1RateCheckRequest = null;
            //var response = instance.CheckRates(v1RateCheckRequest);
            //Assert.IsType<List<RateCheck>>(response);
        }
    }
}
