/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Tusk.Client;
using Tusk.Api;
// uncomment below to import models
//using Tusk.Model;

namespace Tusk.Test.Api
{
    /// <summary>
    ///  Class for testing TrackingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TrackingApiTests : IDisposable
    {
        private TrackingApi instance;

        public TrackingApiTests()
        {
            instance = new TrackingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TrackingApi
            //Assert.IsType<TrackingApi>(instance);
        }

        /// <summary>
        /// Test GetLabelTrackingHistory
        /// </summary>
        [Fact]
        public void GetLabelTrackingHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int labelId = null;
            //var response = instance.GetLabelTrackingHistory(labelId);
            //Assert.IsType<V1TrackingLabelHistoryResponse>(response);
        }

        /// <summary>
        /// Test GetLabelTrackingStatus
        /// </summary>
        [Fact]
        public void GetLabelTrackingStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int labelId = null;
            //var response = instance.GetLabelTrackingStatus(labelId);
            //Assert.IsType<TrackingLabel>(response);
        }

        /// <summary>
        /// Test GetShipmentTracking
        /// </summary>
        [Fact]
        public void GetShipmentTrackingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string trackingNumber = null;
            //var response = instance.GetShipmentTracking(trackingNumber);
            //Assert.IsType<TrackingShipment>(response);
        }
    }
}
