/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        public AddressTests()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Fact]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" Address
            //Assert.IsType<Address>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

        /// <summary>
        /// Test the property 'IsResidential'
        /// </summary>
        [Fact]
        public void IsResidentialTest()
        {
            // TODO unit test for the property 'IsResidential'
        }

        /// <summary>
        /// Test the property 'Street1'
        /// </summary>
        [Fact]
        public void Street1Test()
        {
            // TODO unit test for the property 'Street1'
        }

        /// <summary>
        /// Test the property 'Street2'
        /// </summary>
        [Fact]
        public void Street2Test()
        {
            // TODO unit test for the property 'Street2'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
    }
}
