/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing Delivery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliveryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Delivery
        //private Delivery instance;

        public DeliveryTests()
        {
            // TODO uncomment below to create an instance of Delivery
            //instance = new Delivery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Delivery
        /// </summary>
        [Fact]
        public void DeliveryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Delivery
            //Assert.IsType<Delivery>(instance);
        }

        /// <summary>
        /// Test the property 'ServiceShipSpeedDays'
        /// </summary>
        [Fact]
        public void ServiceShipSpeedDaysTest()
        {
            // TODO unit test for the property 'ServiceShipSpeedDays'
        }

        /// <summary>
        /// Test the property 'EstimatedTimeInTransitDays'
        /// </summary>
        [Fact]
        public void EstimatedTimeInTransitDaysTest()
        {
            // TODO unit test for the property 'EstimatedTimeInTransitDays'
        }

        /// <summary>
        /// Test the property 'EstimatedDeliveryDate'
        /// </summary>
        [Fact]
        public void EstimatedDeliveryDateTest()
        {
            // TODO unit test for the property 'EstimatedDeliveryDate'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
    }
}
