/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing Label
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Label
        //private Label instance;

        public LabelTests()
        {
            // TODO uncomment below to create an instance of Label
            //instance = new Label();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Label
        /// </summary>
        [Fact]
        public void LabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" Label
            //Assert.IsType<Label>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Fact]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }

        /// <summary>
        /// Test the property 'RateId'
        /// </summary>
        [Fact]
        public void RateIdTest()
        {
            // TODO unit test for the property 'RateId'
        }

        /// <summary>
        /// Test the property 'LabelUrl'
        /// </summary>
        [Fact]
        public void LabelUrlTest()
        {
            // TODO unit test for the property 'LabelUrl'
        }

        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Fact]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }

        /// <summary>
        /// Test the property 'TrackingUrl'
        /// </summary>
        [Fact]
        public void TrackingUrlTest()
        {
            // TODO unit test for the property 'TrackingUrl'
        }

        /// <summary>
        /// Test the property 'LabelFormat'
        /// </summary>
        [Fact]
        public void LabelFormatTest()
        {
            // TODO unit test for the property 'LabelFormat'
        }
    }
}
