/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing ManifestException
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManifestExceptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManifestException
        //private ManifestException instance;

        public ManifestExceptionTests()
        {
            // TODO uncomment below to create an instance of ManifestException
            //instance = new ManifestException();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManifestException
        /// </summary>
        [Fact]
        public void ManifestExceptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManifestException
            //Assert.IsType<ManifestException>(instance);
        }

        /// <summary>
        /// Test the property 'LabelId'
        /// </summary>
        [Fact]
        public void LabelIdTest()
        {
            // TODO unit test for the property 'LabelId'
        }

        /// <summary>
        /// Test the property 'ExceptionMessage'
        /// </summary>
        [Fact]
        public void ExceptionMessageTest()
        {
            // TODO unit test for the property 'ExceptionMessage'
        }
    }
}
