/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing ManifestOperationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManifestOperationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManifestOperationResponse
        //private ManifestOperationResponse instance;

        public ManifestOperationResponseTests()
        {
            // TODO uncomment below to create an instance of ManifestOperationResponse
            //instance = new ManifestOperationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManifestOperationResponse
        /// </summary>
        [Fact]
        public void ManifestOperationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManifestOperationResponse
            //Assert.IsType<ManifestOperationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ManifestId'
        /// </summary>
        [Fact]
        public void ManifestIdTest()
        {
            // TODO unit test for the property 'ManifestId'
        }

        /// <summary>
        /// Test the property 'Exceptions'
        /// </summary>
        [Fact]
        public void ExceptionsTest()
        {
            // TODO unit test for the property 'Exceptions'
        }
    }
}
