/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing Manifest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManifestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Manifest
        //private Manifest instance;

        public ManifestTests()
        {
            // TODO uncomment below to create an instance of Manifest
            //instance = new Manifest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Manifest
        /// </summary>
        [Fact]
        public void ManifestInstanceTest()
        {
            // TODO uncomment below to test "IsType" Manifest
            //Assert.IsType<Manifest>(instance);
        }

        /// <summary>
        /// Test the property 'ManifestId'
        /// </summary>
        [Fact]
        public void ManifestIdTest()
        {
            // TODO unit test for the property 'ManifestId'
        }

        /// <summary>
        /// Test the property 'AddressFrom'
        /// </summary>
        [Fact]
        public void AddressFromTest()
        {
            // TODO unit test for the property 'AddressFrom'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'ManifestDocument'
        /// </summary>
        [Fact]
        public void ManifestDocumentTest()
        {
            // TODO unit test for the property 'ManifestDocument'
        }
    }
}
