/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing ManifestLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ManifestLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ManifestLabel
        //private ManifestLabel instance;

        public ManifestLabelTests()
        {
            // TODO uncomment below to create an instance of ManifestLabel
            //instance = new ManifestLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ManifestLabel
        /// </summary>
        [Fact]
        public void ManifestLabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ManifestLabel
            //Assert.IsType<ManifestLabel>(instance);
        }

        /// <summary>
        /// Test the property 'LabelId'
        /// </summary>
        [Fact]
        public void LabelIdTest()
        {
            // TODO unit test for the property 'LabelId'
        }

        /// <summary>
        /// Test the property 'ShipmentTrackingNumber'
        /// </summary>
        [Fact]
        public void ShipmentTrackingNumberTest()
        {
            // TODO unit test for the property 'ShipmentTrackingNumber'
        }
    }
}
