/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing ParcelDimensions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ParcelDimensionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ParcelDimensions
        //private ParcelDimensions instance;

        public ParcelDimensionsTests()
        {
            // TODO uncomment below to create an instance of ParcelDimensions
            //instance = new ParcelDimensions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ParcelDimensions
        /// </summary>
        [Fact]
        public void ParcelDimensionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ParcelDimensions
            //Assert.IsType<ParcelDimensions>(instance);
        }

        /// <summary>
        /// Test the property 'Length'
        /// </summary>
        [Fact]
        public void LengthTest()
        {
            // TODO unit test for the property 'Length'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
    }
}
