/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing Shipment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Shipment
        //private Shipment instance;

        public ShipmentTests()
        {
            // TODO uncomment below to create an instance of Shipment
            //instance = new Shipment();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Shipment
        /// </summary>
        [Fact]
        public void ShipmentInstanceTest()
        {
            // TODO uncomment below to test "IsType" Shipment
            //Assert.IsType<Shipment>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ExternalReference'
        /// </summary>
        [Fact]
        public void ExternalReferenceTest()
        {
            // TODO unit test for the property 'ExternalReference'
        }

        /// <summary>
        /// Test the property 'Confirmation'
        /// </summary>
        [Fact]
        public void ConfirmationTest()
        {
            // TODO unit test for the property 'Confirmation'
        }

        /// <summary>
        /// Test the property 'AddressTo'
        /// </summary>
        [Fact]
        public void AddressToTest()
        {
            // TODO unit test for the property 'AddressTo'
        }

        /// <summary>
        /// Test the property 'AddressFrom'
        /// </summary>
        [Fact]
        public void AddressFromTest()
        {
            // TODO unit test for the property 'AddressFrom'
        }

        /// <summary>
        /// Test the property 'Parcels'
        /// </summary>
        [Fact]
        public void ParcelsTest()
        {
            // TODO unit test for the property 'Parcels'
        }
    }
}
