/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing ShipmentPurchaseResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipmentPurchaseResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipmentPurchaseResponse
        //private ShipmentPurchaseResponse instance;

        public ShipmentPurchaseResponseTests()
        {
            // TODO uncomment below to create an instance of ShipmentPurchaseResponse
            //instance = new ShipmentPurchaseResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipmentPurchaseResponse
        /// </summary>
        [Fact]
        public void ShipmentPurchaseResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipmentPurchaseResponse
            //Assert.IsType<ShipmentPurchaseResponse>(instance);
        }

        /// <summary>
        /// Test the property 'ShipmentId'
        /// </summary>
        [Fact]
        public void ShipmentIdTest()
        {
            // TODO unit test for the property 'ShipmentId'
        }

        /// <summary>
        /// Test the property 'RateId'
        /// </summary>
        [Fact]
        public void RateIdTest()
        {
            // TODO unit test for the property 'RateId'
        }

        /// <summary>
        /// Test the property 'ShipmentTrackingNumber'
        /// </summary>
        [Fact]
        public void ShipmentTrackingNumberTest()
        {
            // TODO unit test for the property 'ShipmentTrackingNumber'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
    }
}
