/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing TrackingLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackingLabel
        //private TrackingLabel instance;

        public TrackingLabelTests()
        {
            // TODO uncomment below to create an instance of TrackingLabel
            //instance = new TrackingLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackingLabel
        /// </summary>
        [Fact]
        public void TrackingLabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackingLabel
            //Assert.IsType<TrackingLabel>(instance);
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Fact]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }

        /// <summary>
        /// Test the property 'DeliveryEta'
        /// </summary>
        [Fact]
        public void DeliveryEtaTest()
        {
            // TODO unit test for the property 'DeliveryEta'
        }
    }
}
