/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing TrackingShipmentLabel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingShipmentLabelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackingShipmentLabel
        //private TrackingShipmentLabel instance;

        public TrackingShipmentLabelTests()
        {
            // TODO uncomment below to create an instance of TrackingShipmentLabel
            //instance = new TrackingShipmentLabel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackingShipmentLabel
        /// </summary>
        [Fact]
        public void TrackingShipmentLabelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackingShipmentLabel
            //Assert.IsType<TrackingShipmentLabel>(instance);
        }

        /// <summary>
        /// Test the property 'LabelId'
        /// </summary>
        [Fact]
        public void LabelIdTest()
        {
            // TODO unit test for the property 'LabelId'
        }

        /// <summary>
        /// Test the property 'FinalMileCarrier'
        /// </summary>
        [Fact]
        public void FinalMileCarrierTest()
        {
            // TODO unit test for the property 'FinalMileCarrier'
        }

        /// <summary>
        /// Test the property 'FinalMileCarrierTrackingNumber'
        /// </summary>
        [Fact]
        public void FinalMileCarrierTrackingNumberTest()
        {
            // TODO unit test for the property 'FinalMileCarrierTrackingNumber'
        }

        /// <summary>
        /// Test the property 'EstimatedDeliveryDate'
        /// </summary>
        [Fact]
        public void EstimatedDeliveryDateTest()
        {
            // TODO unit test for the property 'EstimatedDeliveryDate'
        }

        /// <summary>
        /// Test the property 'TrackingEvents'
        /// </summary>
        [Fact]
        public void TrackingEventsTest()
        {
            // TODO unit test for the property 'TrackingEvents'
        }
    }
}
