/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing TrackingEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackingEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackingEvent
        //private TrackingEvent instance;

        public TrackingEventTests()
        {
            // TODO uncomment below to create an instance of TrackingEvent
            //instance = new TrackingEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackingEvent
        /// </summary>
        [Fact]
        public void TrackingEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackingEvent
            //Assert.IsType<TrackingEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'EventDate'
        /// </summary>
        [Fact]
        public void EventDateTest()
        {
            // TODO unit test for the property 'EventDate'
        }

        /// <summary>
        /// Test the property 'StatusDetail'
        /// </summary>
        [Fact]
        public void StatusDetailTest()
        {
            // TODO unit test for the property 'StatusDetail'
        }
    }
}
