/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing V1LabelsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1LabelsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1LabelsRequest
        private V1LabelsRequest instance;

        public V1LabelsRequestTests()
        {
            // TODO uncomment below to create an instance of V1LabelsRequest
            instance = new V1LabelsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1LabelsRequest
        /// </summary>
        [Fact]
        public void V1LabelsRequestInstanceTest()
        {
            var instance = new V1LabelsRequest
            {
                Shipment = new CreateShipment
                {
                    Parcels = new List<Parcel>()
                    {
                        new Parcel
                        {
                            Dimensions = new ParcelDimensions
                            {
                                Height = 1,
                                Length = 1,
                                Width = 1
                            },
                            Weight = new ParcelWeight
                            {
                                Unit = "Pound",
                                Value = 1
                            }
                        }
                    }
                }
            };
            Assert.IsType<V1LabelsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LabelFormat'
        /// </summary>
        [Fact]
        public void LabelFormatTest()
        {
            // TODO unit test for the property 'LabelFormat'
        }

        /// <summary>
        /// Test the property 'Shipment'
        /// </summary>
        [Fact]
        public void ShipmentTest()
        {
            // TODO unit test for the property 'Shipment'
        }
    }
}
