/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing V1ManifestCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1ManifestCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1ManifestCreateRequest
        //private V1ManifestCreateRequest instance;

        public V1ManifestCreateRequestTests()
        {
            // TODO uncomment below to create an instance of V1ManifestCreateRequest
            //instance = new V1ManifestCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1ManifestCreateRequest
        /// </summary>
        [Fact]
        public void V1ManifestCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1ManifestCreateRequest
            //Assert.IsType<V1ManifestCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LabelIds'
        /// </summary>
        [Fact]
        public void LabelIdsTest()
        {
            // TODO unit test for the property 'LabelIds'
        }

        /// <summary>
        /// Test the property 'ShipmentTrackingNumbers'
        /// </summary>
        [Fact]
        public void ShipmentTrackingNumbersTest()
        {
            // TODO unit test for the property 'ShipmentTrackingNumbers'
        }

        /// <summary>
        /// Test the property 'AddressFrom'
        /// </summary>
        [Fact]
        public void AddressFromTest()
        {
            // TODO unit test for the property 'AddressFrom'
        }
    }
}
