/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing V1RateCheckRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1RateCheckRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1RateCheckRequest
        //private V1RateCheckRequest instance;

        public V1RateCheckRequestTests()
        {
            // TODO uncomment below to create an instance of V1RateCheckRequest
            //instance = new V1RateCheckRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1RateCheckRequest
        /// </summary>
        [Fact]
        public void V1RateCheckRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1RateCheckRequest
            //Assert.IsType<V1RateCheckRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Confirmation'
        /// </summary>
        [Fact]
        public void ConfirmationTest()
        {
            // TODO unit test for the property 'Confirmation'
        }

        /// <summary>
        /// Test the property 'ShipDate'
        /// </summary>
        [Fact]
        public void ShipDateTest()
        {
            // TODO unit test for the property 'ShipDate'
        }

        /// <summary>
        /// Test the property 'AddressFrom'
        /// </summary>
        [Fact]
        public void AddressFromTest()
        {
            // TODO unit test for the property 'AddressFrom'
        }

        /// <summary>
        /// Test the property 'PostalCodeTo'
        /// </summary>
        [Fact]
        public void PostalCodeToTest()
        {
            // TODO unit test for the property 'PostalCodeTo'
        }

        /// <summary>
        /// Test the property 'Parcels'
        /// </summary>
        [Fact]
        public void ParcelsTest()
        {
            // TODO unit test for the property 'Parcels'
        }
    }
}
