/*
 * Tusk Logistics API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: devsupport@tusklogistics.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Tusk.Model;
using Tusk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Tusk.Test.Model
{
    /// <summary>
    ///  Class for testing V1TrackingLabelHistoryResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1TrackingLabelHistoryResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1TrackingLabelHistoryResponse
        //private V1TrackingLabelHistoryResponse instance;

        public V1TrackingLabelHistoryResponseTests()
        {
            // TODO uncomment below to create an instance of V1TrackingLabelHistoryResponse
            //instance = new V1TrackingLabelHistoryResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1TrackingLabelHistoryResponse
        /// </summary>
        [Fact]
        public void V1TrackingLabelHistoryResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1TrackingLabelHistoryResponse
            //Assert.IsType<V1TrackingLabelHistoryResponse>(instance);
        }

        /// <summary>
        /// Test the property 'TrackingEvents'
        /// </summary>
        [Fact]
        public void TrackingEventsTest()
        {
            // TODO unit test for the property 'TrackingEvents'
        }
    }
}
